// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCiTD1t1iL-8hiMpaBZTaAjRH-SwTNKR2A',
    appId: '1:485729663699:web:c90316dec98d433e2df226',
    messagingSenderId: '485729663699',
    projectId: 'soochi-ee23e',
    authDomain: 'soochi-ee23e.firebaseapp.com',
    storageBucket: 'soochi-ee23e.appspot.com',
    measurementId: 'G-VN855ZZ6XC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHbGeSggLXI2Zuz9SWkeh99UtuY8sQY20',
    appId: '1:485729663699:android:77a76e214d6e6ab42df226',
    messagingSenderId: '485729663699',
    projectId: 'soochi-ee23e',
    storageBucket: 'soochi-ee23e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNaGUq_gmVF_3-U9E1blz_AxfVwF3hA88',
    appId: '1:485729663699:ios:de18d3e1d0a4ca7e2df226',
    messagingSenderId: '485729663699',
    projectId: 'soochi-ee23e',
    storageBucket: 'soochi-ee23e.appspot.com',
    iosBundleId: 'com.example.soochi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDNaGUq_gmVF_3-U9E1blz_AxfVwF3hA88',
    appId: '1:485729663699:ios:de18d3e1d0a4ca7e2df226',
    messagingSenderId: '485729663699',
    projectId: 'soochi-ee23e',
    storageBucket: 'soochi-ee23e.appspot.com',
    iosBundleId: 'com.example.soochi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCiTD1t1iL-8hiMpaBZTaAjRH-SwTNKR2A',
    appId: '1:485729663699:web:3510c0cb7d2eca122df226',
    messagingSenderId: '485729663699',
    projectId: 'soochi-ee23e',
    authDomain: 'soochi-ee23e.firebaseapp.com',
    storageBucket: 'soochi-ee23e.appspot.com',
    measurementId: 'G-92SKQXC6CJ',
  );
}
